/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/dkheCyZ3Hqi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import GridBackground from "./GridBackground"
import VideoAd from "../landing/VideoAd"

export function AutoTriggerTabs() {

  return (
    <GridBackground>
      <div className="relative container mx-auto text-white px-5">
      <VideoAd />      
      </div>
    </GridBackground>
    
  )
}
