
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "DCTFUSION",
  description: "Generated by dctfusion",
  icons:'https://dct4life-files.s3.af-south-1.amazonaws.com/uploads/icon.png'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
        {children}  
    </div>
  );
}
